### ISSUE TITLE
Update Windows installation procedure for Verilator

### ISSUE THREAD

**Issue by tuppi-ovh** [SpinalHDL/SpinalDoc-RTD#64]
A clean msys2 installation contains a reference to verilator 4.200 which is not compatible with `SpinalTemplateSbt` project:
```
...
[Progress] Verilator compilation started
In file included from C:/msys64/mingw64/share/verilator/include/verilated_vcd_c.cpp:21:
C:/msys64/mingw64/share/verilator/include/verilated_vcd_c.cpp: In member function 'void VerilatedVcd::dumpHeader()':
C:/msys64/mingw64/share/verilator/include/verilatedos.h:496:37: error: 'localtime_r' was not declared in this scope; did you mean 'localtime_s'?
  496 | # define VL_LOCALTIME_R(timep, tmp) localtime_r((timep), (tmp))
      |                                     ^~~~~~~~~~~
C:/msys64/mingw64/share/verilator/include/verilated_vcd_c.cpp:355:9: note: in expansion of macro 'VL_LOCALTIME_R'
  355 |         VL_LOCALTIME_R(&tick, &ticktm);
      |         ^~~~~~~~~~~~~~
make: *** [/mingw64/share/verilator/include/verilated.mk:241: verilated_vcd_c.o] Error 1
make: *** Waiting for unfinished jobs....
Exception in thread "main" java.lang.AssertionError: assertion failed: Verilator C++ model compilation failed
	at scala.Predef$.assert(Predef.scala:170)
	at spinal.sim.VerilatorBackend.compileVerilator(VerilatorBackend.scala:480)
	at spinal.sim.VerilatorBackend.<init>(VerilatorBackend.scala:542)
	at spinal.core.sim.SpinalVerilatorBackend$.apply(SimBootstraps.scala:135)
	at spinal.core.sim.SpinalSimConfig.compile(SimBootstraps.scala:625)
	at spinal.core.sim.SpinalSimConfig.compile(SimBootstraps.scala:588)
	at spinal.core.sim.SpinalSimConfig.doSim(SimBootstraps.scala:565)
	at mylib.MyTopLevelSim$.main(MyTopLevelSim.scala:13)
	at mylib.MyTopLevelSim.main(MyTopLevelSim.scala)

Process finished with exit code 1
```

An elder version of verilator should be installed by `pacman -U http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-verilator-4.032-1-any.pkg.tar.xz`.

So, this doc section should be updated:

![image](https://user-images.githubusercontent.com/59368736/115926528-45951000-a483-11eb-9a82-a3282cf4b286.png)

**Comment by Dolu1990** [comment]
Thanks ^^
I fixed the doc and also SpinalHDL dev now support both old and upstream Verilator :)
